### ISSUE TITLE
Plugin Crash During terraform import

### ISSUE THREAD

**Issue by ArisBee** [orcasecurity/terraform-provider-orcasecurity#112]
### Terraform Version
Terraform v1.9.1
on darwin_arm64

### provider registry.terraform.io/orcasecurity/orcasecurity v0.0.14 and v0.013
Affected Resource(s)
* orcasecurity_automation

### Terraform Configuration Files
```hcl
terraform {
  required_providers {
    orcasecurity = {
      source  = "orcasecurity/orcasecurity"
      version = "0.0.14"
    }
  }
}

provider "orcasecurity" {
  api_url = "https://ap.eu.orcasecurity.io" # Example API endpoint
  api_key = var.orca_api_key
}

resource "orcasecurity_automation" "critical_alerts_forward" {
  # Resource definition intentionally left empty to show import usage
}
```

### Expected Behavior
The provider should import the resource without crashing, allowing the resource's state to be added to the Terraform state file.

### Actual Behavior
The provider crashes with the following error:

```bash
Error: Plugin did not respond

The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).ReadResource
call. The plugin logs may contain more details.
```

Stack trace from the plugin:

```bash
Stack trace from the terraform-provider-orcasecurity_v0.0.14 plugin:
 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x18 pc=0x1046c3980]
 
goroutine 54 [running]:
terraform-provider-orcasecurity/orcasecurity/api_client.(*APIResponse).StatusCode(...)
        terraform-provider-orcasecurity/orcasecurity/api_client/api_client.go:36
terraform-provider-orcasecurity/orcasecurity/api_client.(*APIClient).IsAutomationExists(0x104a46200?, {0x140004980f0?, 0x104d13fb0?})
        terraform-provider-orcasecurity/orcasecurity/api_client/automations.go:79 +0x70
terraform-provider-orcasecurity/orcasecurity/automations.(*automationResource).Read(0x1400011a028, {0x104d0f2b8, 0x14000214d80}, { { { {0x104d12950, 0x1400050e660}, {0x104c20940, 0x1400050e450} }, {0x104d13fb0, 0x140004b4000} }, 0x1400011a080, ...}, ...)
        terraform-provider-orcasecurity/orcasecurity/automations/resource.go:323 +0x194
[github.com/hashicorp/terraform-plugin-framework/internal/fwserver](http://github.com/hashicorp/terraform-plugin-framework/internal/fwserver).(*Server).ReadResource(0x1400013d8c0, {0x104d0f2b8, 0x14000214d80}, 0x14000214e10, 0x140000df5d0)
        [github.com/hashicorp/terraform-plugin-framework@v1.3.4/internal/fwserver/server_readresource.go:101](http://github.com/hashicorp/terraform-plugin-framework@v1.3.4/internal/fwserver/server_readresource.go:101) +0x4b0
[github.com/hashicorp/terraform-plugin-framework/internal/proto6server](http://github.com/hashicorp/terraform-plugin-framework/internal/proto6server).(*Server).ReadResource(0x1400013d8c0, {0x104d0f2b8?, 0x14000214c30?}, 0x14000478300)
        [github.com/hashicorp/terraform-plugin-framework@v1.3.4/internal/proto6server/server_readresource.go:55](http://github.com/hashicorp/terraform-plugin-framework@v1.3.4/internal/proto6server/server_readresource.go:55) +0x1a8
[github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server](http://github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server).(*server).ReadResource(0x14000133e00, {0x104d0f2b8?, 0x14000214270?}, 0x1400007e600)
        [github.com/hashicorp/terraform-plugin-go@v0.18.0/tfprotov6/tf6server/server.go:749](http://github.com/hashicorp/terraform-plugin-go@v0.18.0/tfprotov6/tf6server/server.go:749) +0x3ec
[github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ReadResource_Handler](http://github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ReadResource_Handler)({0x104cd8c60?, 0x14000133e00}, {0x104d0f2b8, 0x14000214270}, 0x140004000e0, 0x0)
        [github.com/hashicorp/terraform-plugin-go@v0.18.0/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:386](http://github.com/hashicorp/terraform-plugin-go@v0.18.0/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:386) +0x174
[google.golang.org/grpc](http://google.golang.org/grpc).(*Server).processUnaryRPC(0x140002d63c0, {0x104d12ab0, 0x140003fc000}, 0x14000682120, 0x140003b0510, 0x1051988b0, 0x0)
        [google.golang.org/grpc@v1.56.3/server.go:1335](http://google.golang.org/grpc@v1.56.3/server.go:1335) +0xc7c
[google.golang.org/grpc](http://google.golang.org/grpc).(*Server).handleStream(0x140002d63c0, {0x104d12ab0, 0x140003fc000}, 0x14000682120, 0x0)
        [google.golang.org/grpc@v1.56.3/server.go:1712](http://google.golang.org/grpc@v1.56.3/server.go:1712) +0x840
[google.golang.org/grpc](http://google.golang.org/grpc).(*Server).serveStreams.func1.1()
        [google.golang.org/grpc@v1.56.3/server.go:947](http://google.golang.org/grpc@v1.56.3/server.go:947) +0xb4
created by [google.golang.org/grpc](http://google.golang.org/grpc).(*Server).serveStreams.func1
        [google.golang.org/grpc@v1.56.3/server.go:958](http://google.golang.org/grpc@v1.56.3/server.go:958) +0x17c
 
Error: The terraform-provider-orcasecurity_v0.0.14 plugin crashed!
```

**Comment by patrickb-orca** [comment]
Hey ArisBee, thank you for bringing this to my attention. We are pushing automations enhancements very shortly which will add support for email, slack, dismissing alerts, and changing their scores. Once this is pushed, we will support these sorts of automations as manageable resources. More testing will be done at that point to ensure we can properly import those resources.

Are you able to share the full Terraform config code that defines your automation resource?

Thank you!
Patrick

**Comment by patrickb-orca** [comment]
Hi ArisBee, can you see if this latest release solves the issue? Thanks! 
https://registry.terraform.io/providers/orcasecurity/orcasecurity/latest/docs/resources/automation

**Comment by ArisBee** [comment]
Hi @patrickb-orca , the plugin still crashes with the same segmentation fault error during the Read phase using` v0.0.15`.

**Comment by patrickb-orca** [comment]
Hi @ArisBee, are you able to use v0.0.16 (the latest)? I only pushed changes to that tag. If the fixes work, I can add the fixing-code to v0.0.15, if you think that'd be appropriate.

**Comment by ArisBee** [comment]
Hi @patrickb-orca, the problem persists with v0.0.16. I'm sending you the trace-log by email.

**Comment by SecretSquirrel-origami** [comment]
Hi @ArisBee , i experienced a similar issue on v0.0.14, this was caused by a typo in provider for "api_endpoint".

It should be:
api_endpoint = "https://api.eu.orcasecurity.io" 

perhaps that helps.

**Comment by ArisBee** [comment]
Thank you @SecretSquirrel-origami, that was the issue.
